### ISSUE TITLE
Issues Testing v1.0.4

### ISSUE THREAD

**Issue by insomaniac49** [rishikanthc/Scriberr#166]
Hello there! Loving a lot of the additions and UI changes in the latest version, but I am running into a few issues as well as a few suggestions

- GPU transcribing is not working for me, and I am not clear on the requirements for install in the latest
`RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version`
I run an Ollama docker image on the same host and it is able to utilize the GPU, my drivers are also up to date
Running a RTX 3080 with 581.15 drivers

- Cancelling is not working, I ran 2 back to back tests, it receives this command according to the docker logs:
 `2025/09/01 20:27:20 Killing job 28d5c54d-ea13-4cc1-8880-116700bebd8c`
And approximately 10 minutes later the job finally cancels all while CPU usage remains high:
`2025/09/01 20:37:33 Worker 1: Job 28d5c54d-ea13-4cc1-8880-116700bebd8c was cancelled`
After letting the transcription run uninterrupted, it takes 10 minutes to successfully complete almost an identical time period. To me this seems like cancel doesn't work until the job "completes" first. I would expect cancelling to take a minute at most.

For suggestions:

- It would be nice when cancelling a transcription to say "Cancelled" when hovering over the status instead of just "Failed"
- A report somewhere on how long the transcription process took, not a current ETA (though that'd be nice), I'd like to compare how long different models and settings take to run a sample file and compare quality differences. I think this could be accomplished easily enough by comparing these two pieces of data in the logs

`[4.918ms] [rows:1] UPDATE `transcription_jobs` SET `status`="processing",`updated_at`="2025-09-01 21:18:50.861" WHERE id = "28d5c54d-ea13-4cc1-8880-116700bebd8c"`
`[4.007ms] [rows:1] UPDATE `transcription_jobs` SET `status`="completed",`updated_at`="2025-09-01 21:28:29.284" WHERE id = "28d5c54d-ea13-4cc1-8880-116700bebd8c"`

- A way to change the speaker names with diarization before dumping to txt, json etc

- In the timeline view it would be nice to have the option to disable the auto scroll while playing the audio

**Comment by BarbellDwarf** [comment]
Are you running the container with docker compose or a docker run command? if a compose file. could you post that here with the sensitive bits redacted?

**Comment by rishikanthc** [comment]
Hi @insomaniac49 
Great to hear that you're liking the update. 

- regarding the cuda unfortunately I don't have access to my GPUs currently so I wasn't able to test it. I simply pulled the latest cuda image and put my app in there. If you could provide more logs - at container startup, before during and after you start transcription
- I'll look in to this. I tested with short clips and after about a minute it stopped but maybe it's failing when the job is large. I'll fix the bug in a patch. 
- yup changing speaker names is in my plan. Will add it
- so the auto scroll is for the playback follow along so it could always show the current word. I can provide an option to disable it. Would you prefer it disabled ? To still be able to play pause I provide additional playback controls in the bottom left which you can use if that solves your problem. Just looking for feedback on what's the preferred UX
- the other two features - cancelled status and time spent processing can be added. Look out for a future release. 
- regarding eta. That's a bit tricky. I haven't been able to get that working for some reason. 

Thanks for trying the app and bringing up issues. 

@SpirusNox welcome back !! Long time.

**Comment by rishikanthc** [comment]
@insomaniac49 did you check #152 ? Did you add the gpu resources in the compose? Just wanted to check.

**Comment by insomaniac49** [comment]
@rishikanthc Glad to hear most of those features can be added or already planned, :)

- I'll grab some logs tomorrow and upload, after looking at #152 I see my compose was incorrect but it still fails for me
- For the cancel issue I am currently testing with a 5 min audio clip as a point of reference
- I think having the Auto-Scroll active as default is fine, with a lot of speakers the scroll can move fast if I am trying to go back and double check something quick without pausing. I was able to use the Play/Pause button but took me a little to notice it in the corner so maybe a bit larger would be nice

@SpirusNox I am now using the compose from #152 below, previously I was using the basic compose pointing at the latest branch in the installation instructions, I didn't notice info for a differing CUDA install.

```
 services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:v1.0.4-cuda
    container_name: scriberr
    ports:
      - "8080:8080"
    volumes:
      - scriberr_data:/app/data
    restart: unless-stopped
# ----------------- Add the following --------------- 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
# -----------------------------------------------------
volumes:
  scriberr_data:
```
This is now the error I get upon failure when trying to use GPU (With or without diarization enabled):

```
2025/09/01 23:14:03 /src/internal/api/handlers.go:476

[0.295ms] [rows:1] SELECT * FROM `transcription_jobs` ORDER BY created_at DESC LIMIT 10

[GIN] 2025/09/01 - 23:14:03 | 200 |     565.748µs |      172.18.0.1 | GET      "/api/v1/transcription/list?page=1&limit=10"

DEBUG: WhisperX stderr/stdout: INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]

INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []

>>Performing voice activity detection using Pyannote...

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.5.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint whisperx-env/WhisperX/whisperx/assets/pytorch_model.bin`

Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.

Model was trained with torch 1.10.0+cu102, yours is 2.5.1+cu124. Bad things might happen unless you revert torch to 1.x.

>>Performing transcription...

/app/whisperx-env/WhisperX/.venv/lib/python3.11/site-packages/pyannote/audio/utils/reproducibility.py:74: ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.

It can be re-enabled by calling

   >>> import torch

   >>> torch.backends.cuda.matmul.allow_tf32 = True

   >>> torch.backends.cudnn.allow_tf32 = True

See [https://github.com/pyannote/pyannote-audio/issues/1370⁠](https://github.com/pyannote/pyannote-audio/issues/1370) for more details.


  warnings.warn(

Unable to load any of {libcudnn_cnn.so.9.1.0, libcudnn_cnn.so.9.1, libcudnn_cnn.so.9, libcudnn_cnn.so}

Invalid handle. Cannot load symbol cudnnCreateConvolutionDescriptor


2025/09/01 23:14:03 Worker 1: Failed to process job 28d5c54d-ea13-4cc1-8880-116700bebd8c: WhisperX execution failed: exit status 134
```

**Comment by samhodge-aiml** [comment]
Why am I getting this error
`scriberr  | DEBUG: WhisperX stderr/stdout: /usr/local/bin/python: No module named whisperx`

Using the `docker-compose.yml` snipper from the v1.0.4-cuda image?

**Comment by nebulakid** [comment]
> Why am I getting this error `scriberr | DEBUG: WhisperX stderr/stdout: /usr/local/bin/python: No module named whisperx`
> 
> Using the `docker-compose.yml` snipper from the v1.0.4-cuda image?

Unfortunately same for me.

Here my docker compose file:
```yaml
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:latest
    container_name: scriberr
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_PATH=/app/data/scriberr.db
      - UPLOAD_DIR=/app/data/uploads
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped

```

**Comment by rishikanthc** [comment]
@samhodge-aiml amd @nenkoru hi !
Refer to #152 someone was able to get the cuda image working. For now you can follow the steps outlined there. I'll update the dockerfile and push out a new cuda image with the issue fixed.

**Comment by rishikanthc** [comment]
Just pushed an updated cuda image v1.0.4-cuda with the changes mentioned in #152 
Would be great if one of you could confirm it's working.

**Comment by nenkoru** [comment]
> @samhodge-aiml amd @nenkoru hi !
> Refer to #152 someone was able to get the cuda image working. For now you can follow the steps outlined there. I'll update the dockerfile and push out a new cuda image with the issue fixed. 

I don't really use CUDA within docker images in general as I still find the support for it cumbersome and not worth the hustle unless it is a production where containerisation is vital.
Just deployed an lxc container with gpu sharing and host Scriberr there directly. 
Works fine for me.

As well as that I also self host on-demand gaming environments like this using https://games-on-whales.github.io
And vllm all utilising their own lxc.

**Comment by insomaniac49** [comment]
@rishikanthc Hey I did some testing but I am still running into the same error with the latest image. I am not really a docker expert and am seeing a variety of docker-compose being offered up and they all throw the same error for me. 

I was also going to test the manual install of cuDNN 9.1.x but I am not sure where I am supposed to run these commands.

Edit: After using the docker-compose as provided by rishikanthc

```
version: "3.9"
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:v1.0.4-cuda
    ports:
      - "8080:8080"
    volumes:
      - scriberr_data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  scriberr_data: {}
```

And then using the Docker terminal and running the commands from #152 I was able to successfully get the GPU transcription to work. But it still does not work without manually installing.

**Comment by rishikanthc** [comment]
@insomaniac49 just pushed v1.1.0 which adds all the features you asked for and fixes the job termination. When you stop a job it will now terminate the job immediately. 

Edit cuda support is still not fixed. I need to figure out the Dockerfile.

**Comment by insomaniac49** [comment]
@rishikanthc Awesome I noticed some of the additions while testing the latest 1.04 cuda image.

I was able to get CUDA working again manually with v1.1.0 and confirm that cancelling works right away, thank you!! It does just say failed on hover over instead of cancelled but that's minor. 

Love the info section, it will be great for comparing results and fine tuning settings and changing speaker names is great. I did not see a way to disable auto scroll while playing audio in the timeline view but also minor. Awesome stuff so far!

**Comment by insomaniac49** [comment]
I think I'll close this as the new release covers most of it and the CUDA bug has focus in #152
