### ISSUE TITLE
Project is not working with Nvidia GTX Series 10

### ISSUE THREAD

**Issue by ManuEZ** [rishikanthc/Scriberr#273]
As the title says, when trying to use CUDA, it says that the version of PyTorch doesnt work with sm_61. It says that in order to properly work we need to use pytorch with cu126

The error is the following:

/app/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:283: UserWarning:

Found GPU0 NVIDIA GeForce GTX 1070 Ti which is of cuda capability 6.1.

Minimum and Maximum cuda capability supported by this version of PyTorch is (7.0) - (12.0)

NVIDIA GeForce GTX 1070 Ti with CUDA capability sm_61 is not compatible with the current PyTorch installation.

The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.

If you want to use the NVIDIA GeForce GTX 1070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/.

Please install PyTorch with a following CUDA configurations: 12.6

**Comment by rishikanthc** [comment]
This is a cuda compatibility issue. The current image uses cuda 12.9
I can release another image for older gpus.

**Comment by ManuEZ** [comment]
> This is a cuda compatibility issue. The current image uses cuda 12.9 I can release another image for older gpus.

That would be awesome! I would really appreciate it, I tried to do it on my own but I couldn't :(. I'm a newbie 😅. Thanks so much!

**Comment by teije** [comment]
I would really really appreciate this as well! 

I tried using a GTX 1070 and am now falling back to my CPU, but it takes forever to transcribe a 15 minute file.

**Comment by teije** [comment]
I have attempted to create an image with a lower cuda version, but I kept running into problems that I could not resolve myself. 

@rishikanthc: If it is not too much work, could you release an image based on the lower cuda version?

**Comment by rishikanthc** [comment]
@ManuEZ @teije for sure. Currently I'm planning to publish 3 images for the next release: arm/amd64 cpu, a nvidia cuda-12.9 and a nvidia cuda-12.6

It would be great if you guys can confirm that cuda-12.6 will work with gtx 1080. If not let me know which is the latest cuda version that works with 1080 gpus

**Comment by ManuEZ** [comment]
> [@ManuEZ](https://github.com/ManuEZ) [@teije](https://github.com/teije) for sure. Currently I'm planning to publish 3 images for the next release: arm/amd64 cpu, a nvidia cuda-12.9 and a nvidia cuda-12.6
> 
> It would be great if you guys can confirm that cuda-12.6 will work with gtx 1080. If not let me know which is the latest cuda version that works with 1080 gpus

@rishikanthc Yes, gtx 1080 is Compute Capability of 6.1, Arch Pascal, in other words, yes, cuda 12.6 would work for gtx 1080 as well

**Comment by teije** [comment]
@rishikanthc @ManuEZ Can confirm!

https://developer.nvidia.com/cuda-legacy-gpus

**Comment by rishikanthc** [comment]
@ManuEZ and @teije I have downgraded the base cuda image to use cudnn 12.6.3 instead of 12.9
It works fine on my RTX A5000 which is a newer card. So I guess I don't need to release 2 different cuda images. 
Could one of you build the image from the main branch and test if it works for you ? Would be of great help.

**Comment by teije** [comment]
@rishikanthc I would be happy to help! However, I have never build an image before of a project like this. 
Do you happen to have instructions on how to do this?

**Comment by rishikanthc** [comment]
@teije no worries at all. 
First clone this repo on your machine and cd into it. Then all you need to do is run 
`sudo docker compose -f Dockerfile.cuda up --build`

Let me know how it goes.

**Comment by teije** [comment]
I will give it a try and report back!

**Comment by teije** [comment]
@rishikanthc I have installed docker desktop on my Windows 11 machine and ran the command. Briefly a terminal/log window flashes, but nothing else seems to happen. 

What should happen when I run this command?

**Comment by teije** [comment]
Okay, here I am once again, back with results:
- I have attempted to build the image on windows, but for some reason was unable to
- I was able to succesfully build the image on my Unraid server (logs are attached)
- I am unable to sucessfully transcribe a file using my GPU. A transcription fails with the following message:
    ```    
    /app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 1070 which is of cuda capability 6.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.0) - (12.0)
    
    warnings.warn(
       /app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:304: UserWarning: 
       Please install PyTorch with a following CUDA
       configurations:  12.6 following instructions at
       https://pytorch.org/get-started/locally/
    
    warnings.warn(matched_cuda_warn.format(matched_arches))
    /app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:326: UserWarning: 
    NVIDIA GeForce GTX 1070 with CUDA capability sm_61 is not compatible with the current PyTorch installation.
    The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
    If you want to use the NVIDIA GeForce GTX 1070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
    ```    

~@rishikanthc Is it possible for you to create a version for CUDA 12.6?~

Edit: 
- I just looked at the dockerfile, which already instructs to use CUDA 12.6, going to dig deeper into what I am doing wrong.
- When running this command:
    `sudo docker compose -f Dockerfile.cuda up --build`
    I get the following error:
    `yaml: unmarshal errors: line 7: cannot unmarshal !!str 'FROM no...' into cli.named`
    I am not sure yet why this error occurred, but this lead me to run the following command instead, which sucessfully got the container to run:
    `docker compose -f docker-compose.build.cuda.yml up --build`
    I am new to running docker containers, so I cannot really tell the practical difference between the suggested command and the one that ended up working.

@rishikanthc: To be continued! I will keep troubleshooting, meanwhile: do you happen to have tips for me on how to best continue?

---

My GPU seems to be properly detected inside the container:
``` bash
> docker exec -it scriberr nvidia-smi

Thu Dec  4 10:48:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070        Off |   00000000:01:00.0 Off |                  N/A |
| 33%   25C    P8             10W /  190W |       3MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

[scriberr-logs-startup.txt](https://github.com/user-attachments/files/23930829/scriberr-logs-startup.txt)

[scriberr-unraid-container-logs-register-account_default-cuda-model_and_start-transcription.txt](https://github.com/user-attachments/files/23931388/scriberr-unraid-container-logs-register-account_default-cuda-model_and_start-transcription.txt)

[scriberr-gui-logs-transcription-failed.txt](https://github.com/user-attachments/files/23931391/scriberr-gui-logs-transcription-failed.txt)

**Comment by ManuEZ** [comment]
In my case, I managed to deploy it on Windows, and I got the next error after trying to transcribe:

time=04:28:47 level=ERROR msg="Job processing failed" worker_id=0 job_id=4bf1d168-6070-4ab8-995d-aabc1d427e7e error="single-track processing failed: transcription failed: WhisperX execution failed: exit status 1\nLogs:\nx-env/WhisperX/whisperx/vads/pyannote.py\", line 48, in load_vad_model\n    vad_pipeline = VoiceActivitySegmentation(segmentation=vad_model, device=torch.device(device))\n  File \"/app/data/whisperx-env/WhisperX/whisperx/vads/pyannote.py\", line 199, in __init__\n    super().__init__(segmentation=segmentation, fscore=fscore, use_auth_token=use_auth_token, **inference_kwargs)\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/pyannote/audio/pipelines/voice_activity_detection.py\", line 128, in __init__\n    self._segmentation = Inference(model, **inference_kwargs)\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/pyannote/audio/core/inference.py\", line 114, in __init__\n    self.model.to(self.device)\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py\", line 55, in to\n    return super().to(*args, **kwargs)\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1369, in to\n    return self._apply(convert)\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 928, in _apply\n    module._apply(fn)\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py\", line 291, in _apply\n    self._init_flat_weights()\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py\", line 215, in _init_flat_weights\n    self.flatten_parameters()\n  File \"/app/data/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py\", line 272, in flatten_parameters\n    torch._cudnn_rnn_flatten_weight(\ntorch.AcceleratorError: CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n"


I think it has something to do with PyTorch using a version that doesnt have CUDA 12.6

@rishikanthc

**Comment by teije** [comment]
I have made another attempt (which failed sadly), but this time I used the following command to build the image:
`docker build -f Dockerfile.cuda -t scriberr-cuda:latest .`

This command actually uses the Dockerfile.cuda, which I don't think I did in my previous attempt(?)

These were my steps (and logs of this can be found in the attachment):

1. Build image using:
    `docker build -f Dockerfile.cuda -t scriberr-cuda:latest .`
2. Start container using the cuda compose file in the project root
3. Load UI, works OK
4. Create admin account, works OK
5. Upload mp3 file, works OK
6. Start transcription, fails with the following message (I extracted the most useful text I think, the full thing is in the attached logs):
    ```
    ..
    Found GPU0 NVIDIA GeForce GTX 1070 which is of cuda capability 6.1.
    		Minimum and Maximum cuda capability supported by this version of PyTorch is
    		(7.0) - (12.0)
    ..
    /app/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:304: UserWarning: 
	Please install PyTorch with a following CUDA
	configurations:  12.6 following instructions at
	https://pytorch.org/get-started/locally/
    warnings.warn(matched_cuda_warn.format(matched_arches))
	/app/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:326: UserWarning: 
    NVIDIA GeForce GTX 1070 with CUDA capability sm_61 is not compatible with the current PyTorch installation.
    The current PyTorch install supports CUDA capabilities sm_70 sm_75 sm_80 sm_86 sm_90 sm_100 sm_120.
    If you want to use the NVIDIA GeForce GTX 1070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
    ..
    torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
    ```

@rishikanthc : I don't think that I will be able to resolve this issue with my own limited knowledge.
Do you have enough information (and time?) to create a fix? Would be greatly appreciated and if you need me to test more, let me know!

fyi: @ManuEZ

[logs-new-attempt-deploying-container.txt](https://github.com/user-attachments/files/23958105/logs-new-attempt-deploying-container.txt)

**Comment by rishikanthc** [comment]
@teije Apologies. I think i gave you the wrong command. Can you run this command get back to me with results?
Before running this please ensure that you have pulled the latest commits from the main branch.
`sudo docker compose -f docker-compose.build.cuda.yml up --build`

That should start the cuda container.. It would also be great if you can run nvidia-smi inside the container and show me the output as well to verify the cuda version.. 
Thanks for testing and sharing detailed logs.
I think the above command should work for you.

**Comment by rishikanthc** [comment]
@ManuEZ can you check the cuda version once ?
That's so weird.. Which dockerfile are you using ? 
Please try this command `sudo docker compose -f docker-compose.build.cuda.yml up --build`
and get back to me

**Comment by ManuEZ** [comment]
@rishikanthc Hi, I did try that command and that's how I got that result. The cuda version when I checked was 12.6, but somehow it's still showing 12.9 with pytorch

**Comment by rishikanthc** [comment]
@ManuEZ hmm.. did you clear the old whisperx env ??
Basically do a fresh deploy.. delete the old whisperx env folder so the old environment is deleted.. I want to make sure it's not using the older python environment from previous deployments.. can you try that and get back to me?? If you are available right now, we can resolve it quickly.. I'm working on this issue right now..

**Comment by rishikanthc** [comment]
@ManuEZ and @teije 
I found the issue.. The problem was the torch version installed were for the latest cuda release.. So I had to pin them down to use cuda12.6 
From my testing it seems to work.. 
I merged the changes into the main branch..
Can you test it out ?

1. Delete the previous whisperx-env folder complete - this would be the `whisperx-env` folder to remove the previous env configurations. This is very important ! Without this, the new changes will not be propagated and scriberr will continue using the older incorrect environment
2. Run `sudo docker compose -f docker-compose.build.cuda.yml up --build`

And hopefully you should be able to transcribe successfully.. let me know how it goes

**Comment by ManuEZ** [comment]
@rishikanthc Yep, that's the issue I found too, torch is using latest cuda or v12.9 instead of one for v12.6. And yes, I tried on a clean environment before, let me go ahead and try again

**Comment by teije** [comment]
@rishikanthc Thanks for the response, I will give this a try tomorrow or the day after!

**Comment by rishikanthc** [comment]
@teije and @ManuEZ any luck ?

**Comment by teije** [comment]
@rishikanthc 🥳 !!!

An audio recording was transcribed succesfully using my GPU!
Do you happen to know how much VRAM is required for the models small, medium and large? When using the large model I get an out of memory exception. But I am not quite sure if this is GPU memory or regular memory.

**Comment by rishikanthc** [comment]
@teije phewww finally !! I'm so happy. This issue has been plaguing the app for a while now xD glad it's working now. 

These are rough estimates:
For fp16
Small ~600MB   
Medium ~1.5GB   
Large ~4.5GB   

For int8
Small ~400MB
Medium ~1GB
Large ~3GB

Don't quote me on this numbers. They're approximations based on param counts. 

One more thing. This is just the size for loading the models. Your audio will also add to this (based on the batch size you use). 

I think large can run on a 1080p if you use int8. Float32 (which is the default selection) will not fit on a 8GB card.

**Comment by teije** [comment]
@rishikanthc Thanks for your help and making this app available! Do you have a way for me to buy you a coffee or a beer? :)

I am still tweaking the settings and I am starting to understand what they do.

**Comment by rishikanthc** [comment]
@teije yeah there's a buy me a coffee button both on the repo homepage and app website. 
Thanks for supporting the project and I appreciate your help and patience while I figured out this issue :)

**Comment by teije** [comment]
Awesome. No worries, helping resolve these issues is the least I can do when using the application for free :)

Do you happen to know when the 1.2.0 milestone and image will be released?

I hoped to be able to create an Unraid template for Scriberr

**Comment by rishikanthc** [comment]
@teije I'm targetting to release 1.2.0 by this weekend. Currently trying to optimize the performance of the frontend and also refining and enhancing it.. it's coming along quite great.. so I expect this to be out by Sat/Sun.. I know it's been a long time.. but hopefully this time it should be out..

and an Unraid template would be awesome.. There's an existing unraid template which is super out of date (It uses 0.4.x) and quite a few users came here with issues because they it was running the old version.. I'm not familiar with Unraid templates and from my research it looks like I need to open a thread in their forum and actively maintain it.. I don't have the bandwidth for that currently.. So if you could help me out with that it would be awesome.. I can add a link to your Unraid template so other users can also use it..

**Comment by ManuEZ** [comment]
@rishikanthc AYOOOOOOOOOOOOOOOOOOOOO IT WORKED!!! Sorry, it took me so long to post an update. I tried using a 1 hour long video and it did work! Now is using my old GPU. 10/10. I also confirm that this is fixed now

**Comment by rishikanthc** [comment]
@ManuEZ awesome !! Closing the issue as completed after so long.
