### ISSUE TITLE
Many problems here with CUDA/docker on debian (dependency-problems + first initialiazation + transcriptions)

### ISSUE THREAD

**Issue by michauk** [rishikanthc/Scriberr#387]
Hello there,
The project seems really good, but I encounter some problems, no matter what I try.

### Environment
I'm running a Debian 13 + docker (docker's repo) + nvidia open drivers + cuda toolkit + container toolit.
Hardware : RTX 5070Ti + a *lot* of RAM (512GB).
_Note: cuda upgraded to 13.1 recently (following the repo's releases), when debian upgraded to 13.3, kernel revision and so on. nvidia drivers upgraded 590.48.x_

### docker images used
As there is no prebuilt blackwell image, I built it as specified in the doc+yml.
I also tried the prebuilt CUDA:v1.2.0 in case. I won't describe the problems in this case, because of dependency-problems when transcripting, problems I can admit because of old libs for a blackwell environment/hardware.

### Problem 1) DB iniatialization & permissions problems (for both images by the way)
As stated in the doc, some permission problems might appear with the 2 volumes on the host. The best solution I found is to force the entrypoint to /app/scriberr in the docker-compose.yml for 2nd and future starts. Some problem with the ubuntu/appuser and the OS user mapping?

### Problem 2) dependency problem for parakeet (both images)
As mentionned in [bug 384](https://github.com/rishikanthc/Scriberr/issues/384), parakeet won't build. Not a major problem as there are other models available.

### Problem 3) Transcription failed - focus on blackwell locally built model, based on **docker-compose.build.blackwell.yml** and Dockerfile.cuda.12.9 - but I use 13.1, following nvidia's official releases).

**With whisper / GPU : no matter what the model size and standard settings, it ends up with :**
Fails with :
`scriberr-local-blackwell  | time=11:23:43 level=ERROR msg="Job processing failed" worker_id=0 job_id=1a76f472-88fc-4b95-a1c3-daa7169b0c9a error="single-track processing failed: transcription failed: WhisperX execution failed: exit status 1\nLogs:\n/1370 for more details.\n\n  warnings.warn(\n2026-01-16 11:23:41 - whisperx.asr - INFO - Detected language: fr (0.22) in first 30s of audio\nTraceback (most recent call last):\n  File \"/root/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/root/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/app/whisperx-env/WhisperX/whisperx/__main__.py\", line 102, in <module>\n    cli()\n  File \"/app/whisperx-env/WhisperX/whisperx/__main__.py\", line 98, in cli\n    transcribe_task(args, parser)\n  File \"/app/whisperx-env/WhisperX/whisperx/transcribe.py\", line 150, in transcribe_task\n    result: TranscriptionResult = model.transcribe(\n  File \"/app/whisperx-env/WhisperX/whisperx/asr.py\", line 261, in transcribe\n    for idx, out in enumerate(self.__call__(data(audio, vad_segments), batch_size=batch_size, num_workers=num_workers)):\n  File \"/app/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py\", line 126, in __next__\n    item = next(self.iterator)\n  File \"/app/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py\", line 127, in __next__\n    processed = self.infer(item, **self.params)\n  File \"/app/whisperx-env/WhisperX/.venv/lib/python3.10/site-packages/transformers/pipelines/base.py\", line 1374, in forward\n    model_outputs = self._forward(model_inputs, **forward_params)\n  File \"/app/whisperx-env/WhisperX/whisperx/asr.py\", line 165, in _forward\n    outputs = self.model.generate_segment_batched(model_inputs['inputs'], self.tokenizer, self.options)\n  File \"/app/whisperx-env/WhisperX/whisperx/asr.py\", line 60, in generate_segment_batched\n    encoder_output = self.encode(features)\n  File \"/app/whisperx-env/WhisperX/whisperx/asr.py\", line 99, in encode\n    return self.model.encode(features, to_cpu=to_cpu)\nRuntimeError: CUDA failed with error out of memory\n"`
Memory problem must be a consequence of something else, considering my hardware.

** With whisper / CPU (in case there's something wrong with my nvidia setup - which I doubt)
Transcription is working 👌 **

** With nvidia canary :**
Fails because of language:
`scriberr-local-blackwell  | time=11:37:39 level=ERROR msg="Job processing failed" worker_id=0 job_id=1a76f472-88fc-4b95-a1c3-daa7169b0c9a error="single-track processing failed: transcription failed: Canary execution failed: exit status 2\nLogs:\n\x96\x88████▏| 330M/360M [00:01<00:00, 293MB/s]\r 99%|█████████▉| 358M/360M [00:01<00:00, 293MB/s]\r100%|██████████| 360M/360M [00:01<00:00, 288MB/s]\n2026-01-16 11:30:32 - whisperx.transcribe - INFO - New language found (fr)! Previous was (en), loading new alignment model for new language...\nDownloading: \"https://download.pytorch.org/torchaudio/models/wav2vec2_voxpopuli_base_10k_asr_fr.pt\" to /root/.cache/torch/hub/checkpoints/wav2vec2_voxpopuli_base_10k_asr_fr.pt\n\r  0%|          | 0.00/360M [00:00<?, ?B/s]\r  6%|▌         | 21.5M/360M [00:00<00:01, 225MB/s]\r 14%|█▎        | 49.5M/360M [00:00<00:01, 265MB/s]\r 22%|██▏       | 77.5M/360M [00:00<00:01, 278MB/s]\r 29%|██▉       | 106M/360M [00:00<00:00, 284MB/s] \r 37%|███▋      | 134M/360M [00:00<00:00, 288MB/s]\r 45%|████▍     | 162M/360M [00:00<00:00, 290MB/s]\r 53%|█████▎    | 190M/360M [00:00<00:00, 291MB/s]\r 60%|██████    | 218M/360M [00:00<00:00, 292MB/s]\r 68%|██████▊   | 246M/360M [00:00<00:00, 293MB/s]\r 76%|███████▌  | 274M/360M [00:01<00:00, 293MB/s]\r 84%|████████▍ | 302M/360M [00:01<00:00, 293MB/s]\r 92%|█████████▏| 330M/360M [00:01<00:00, 293MB/s]\r 99%|█████████▉| 358M/360M [00:01<00:00, 293MB/s]\r100%|██████████| 360M/360M [00:01<00:00, 288MB/s]\n2026-01-16 11:30:34 - whisperx.transcribe - INFO - Performing alignment...\nerror: Distribution 'lilcom==1.8.2 @ registry+https://pypi.org/simple' can't be installed because it doesn't have a source distribution or wheel for the current platform\n\nhint: You're on Linux ('manylinux_2_39_x86_64'), but 'lilcom' (v1.8.2) only has wheels for the following platforms: 'manylinux_2_17_aarch64', 'manylinux2014_aarch64', 'macosx_10_13_universal2', 'win_amd64'; consider adding \"sys_platform == 'linux' and platform_machine == 'x86_64'\" to 'tool.uv.required-environments' to ensure uv resolves to a version with compatible wheels\n`

Regards. Tell me if I can do some tests for this specific hardware.

**Comment by vikcious** [comment]
> ### Problem 1) DB iniatialization & permissions problems (for both images by the way)
> As stated in the doc, some permission problems might appear with the 2 volumes on the host. The best solution I found is to force the entrypoint to /app/scriberr in the docker-compose.yml for 2nd and future starts. Some problem with the ubuntu/appuser and the OS user mapping?
> 

Wow, you're a saviour, thank you! For the others, comment out the "ENTRYPOINT ["docker-entrypoint.sh"]" line in your Dockerfile.cuda.12.9 /Dockerfile.cuda file and you're good to go.

#Use entrypoint script that handles user switching and permissions
#ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/app/scriberr"]

**Comment by vikcious** [comment]
> INFO - Performing alignment...\nerror: Distribution 'lilcom==1.8.2 @ registry+https://pypi.org/simple' can't be installed because it doesn't have a source distribution or wheel for the current platform\n\nhint: You're on Linux ('manylinux_2_39_x86_64'), but 'lilcom' (v1.8.2) only has wheels for the following platforms: 'manylinux_2_17_aarch64', 'manylinux2014_aarch64', 'macosx_10_13_universal2', 'win_amd64'; consider adding \"sys_platform == 'linux' and platform_machine == 'x86_64'\" to 'tool.uv.required-environments' to ensure uv resolves to a version with compatible wheels\n`
> 
This is broken since there is no amd64 linux wheel built for lilcom... maybe an email to the maintainer of the pip rep could help.
Also, I have tried the brew installation and sadly it's worse... I mean if one is ready to give up on all "normal" Ubuntu & others way of installing the python, pip, uv and codependecies, maybe one could also integrate the missing "lilcom" to the "parakeet/" .venv. I have given up since on my UBuntu it would turn everyhing python related upside down....

**Comment by vikcious** [comment]
I might have found a solution for the lilcom missing the x86_64 wheels for 1.8.2 version, before I get to ask the maintainers to create and add it. It looks like v1.8.1 has all the needed wheels uploaded hence I though I'd try, why not... :) 

Basically in "/app/whisperx-env/parakeet" there is the uv.lock file that needs to to be amended. The entire "paragraph" related to llicom should be replaced with: 

[[package]]
name = "lilcom"
version = "1.8.1"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "numpy" },
]
wheels = [
    { url = "https://files.pythonhosted.org/packages/e3/6e/7868a5a90e66fefa60642682f5551cb75e489c603f155367003b88363af3/lilcom-1.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:08ba2cf1cd9a175ec3b791ea727e981a1cd25a03d39c32264d651bc52e7e5c33", size = 92958, upload-time = "2025-04-02T04:54:48.125Z" },
]

If you're installing wheel for a different Python version, please check the right download file reference at: https://pypi.org/project/lilcom/1.8.1/#files

For me this solved the bug:
time=17:00:06 level="INFO " msg="Downloading Parakeet model" path=/app/whisperx-env/parakeet/parakeet-tdt-0.6b-v3.nemo
time=17:00:06 level="INFO " msg="Sortformer environment already ready"
time=17:00:06 level="INFO " msg="diarization model initialized" model_id=sortformer
Downloading parakeet-tdt-0.6b-v3.nemo: 1% (23.9 MB / 2.3 GB)
...
Downloading parakeet-tdt-0.6b-v3.nemo: 38% (909.4 MB / 2.3 GB)time=17:07:00 level=ERROR msg="Failed to initialize transcription model" model_id=parakeet error="failed to download Parakeet model: failed to download Parakeet model: failed to save file: read tcp 172.21.0.2:43640->3.162.79.106:443: read: connection reset by peer"
time=17:07:00 level="WARN " msg="Some models failed to initialize" error_count=1

07:00 level="WARN " msg="Model initialization error" error="transcription model parakeet: failed to download Parakeet model: failed to download Parakeet model: failed to save file: read tcp 172.21.0.2:43640->3.162.79.106:443: read: connection reset by peer"
time=17:07:00 level="INFO " msg="Model initialization completed"
time=17:07:00 level="INFO " msg="Unified transcription service initialized successfully"
[+] Initializing quick transcription service
[+] Starting background processing
**time=17:07:00 level="INFO " msg="Scriberr is ready" url=http://0.0.0.0:8085**

**Comment by vikcious** [comment]
Ok, going the extra mile, here is the entire list of .whl for lilcom==1.8.1
==========================================================

[[package]]
name = "lilcom"
version = "1.8.1"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "numpy" },
]
wheels = [
    { url = "https://files.pythonhosted.org/packages/0f/a4/f5d186d5d32364c1e4fe9d7144f378a321f908fdd440e1c9705271bf2350/lilcom-1.8.1-cp37-cp37m-win_amd64.whl", hash = "sha256:1dc594e7059ac09c80a0f02cb68c9cc61e0fd7e0e6a612495b85e859346e212e", size = 68858, upload-time = "2025-04-02T02:52:26.539149Z" },
    { url = "https://files.pythonhosted.org/packages/19/8a/d7e9eb6d0d7ac2fd2b2f8ba2bdc8962792d90dd4ae8296931826245734d2/lilcom-1.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:58603e24fea49fa58abc835803b04de7c067b75a9bd5cc86f6c1fa29cd4bf179", size = 92394, upload-time = "2025-04-02T02:53:31.408945Z" },
    { url = "https://files.pythonhosted.org/packages/1f/58/f1ce0b67a144a2f34828c73df8dd362500031ff07482eac8b985a93a8456/lilcom-1.8.1-cp313-cp313-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:0c4bc1281e1d40163fc438abdd48ac71dbe04bb1e10ef62761b446339f763bb0", size = 86850, upload-time = "2025-04-02T02:51:24.879856Z" },
    { url = "https://files.pythonhosted.org/packages/20/80/0d07c944a09bfed9038121bf3d662e4f5cf56f7f8c2be3669269ceec429b/lilcom-1.8.1-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:834df2155ee7cad41cc5cc482bae764c89ebbaee623cb4788a3b7bbdcd2d22d3", size = 86841, upload-time = "2025-04-02T02:50:18.109075Z" },
    { url = "https://files.pythonhosted.org/packages/36/c6/49b67e55704eb4252966610d35dee6256425209b2ea9be667388d58cba62/lilcom-1.8.1-cp311-cp311-win_amd64.whl", hash = "sha256:af2585d979b8a92fd2f882a5e7320391e7131a98c47200c3668ef7bb7f061926", size = 69181, upload-time = "2025-04-02T02:52:12.311507Z" },
    { url = "https://files.pythonhosted.org/packages/4c/8c/092597769a87a3158906e1ec6732281c67eeb8db81ebbc3568b0331585c1/lilcom-1.8.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:f3489e24e36586aafe723b3f8b140ae60371cb0f1bfecee634f1fee4d64e947a", size = 86834, upload-time = "2025-04-02T02:51:54.747464Z" },
    { url = "https://files.pythonhosted.org/packages/4c/e6/4e96bbeae95338e22aaba683829247f074b1e1455b836ad2260d606b1571/lilcom-1.8.1-cp38-cp38-win_amd64.whl", hash = "sha256:346a39b268f7975e8c8513d93bdf232cd07ddda2c15bedc0a024d6c6c6a6f6fa", size = 68462, upload-time = "2025-04-02T02:51:42.053427Z" },
    { url = "https://files.pythonhosted.org/packages/56/5a/eee3e4afd3dcf3c23ff6e9899098abf94a661bc5eb474ca366c57142338f/lilcom-1.8.1-cp313-cp313-win_amd64.whl", hash = "sha256:5af35273eab932a6b84612bd1597863465078654f40b98a9f8e2d6f67d9f6ebc", size = 69719, upload-time = "2025-04-02T02:51:29.651603Z" },
    { url = "https://files.pythonhosted.org/packages/58/f2/07e6b07c4c3d9e17b62df012235b78e09efa89213970d57ab83f202cb7af/lilcom-1.8.1-cp38-cp38-macosx_10_9_universal2.whl", hash = "sha256:ac8d54c0feb01056df2d6acc947edbcbdf725e9c8b5daf592519e2c8f4ba7259", size = 121976, upload-time = "2025-04-02T02:52:52.778850Z" },
    { url = "https://files.pythonhosted.org/packages/58/fd/8008d8b82965eeb2e35a46edb118e195d10bc424e3d80f2e3dafe3044e1f/lilcom-1.8.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:6b7c5488267c9c3c6ab49c3e3ec287031029d7de57f4c2307264dd75f5e77211", size = 86593, upload-time = "2025-04-02T02:49:39.883439Z" },
    { url = "https://files.pythonhosted.org/packages/5c/a5/3da24b27e60dce949675b2422bb58471de6268940ecf59d5238a3ad8ddb9/lilcom-1.8.1-cp311-cp311-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:9127afa12130c2421b6906c4ff77772f132f87b085404a1cf2486bbb4f37f1a5", size = 100600, upload-time = "2025-04-02T02:53:32.427798Z" },
    { url = "https://files.pythonhosted.org/packages/60/06/aea590f3c031da7341ef4f99397b72bdd8b2f310308c908ef64ed8a6da03/lilcom-1.8.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:d41d3eb7f3a0f61b3564ff25190944d2c2cd388d61847c39471e32ad8f3da7fa", size = 86332, upload-time = "2025-04-02T02:52:03.713601Z" },
    { url = "https://files.pythonhosted.org/packages/67/7e/c20263fb8ed5f5a86fbf3b725ad6e71963e97f8d53e9be61e6cd59067a5f/lilcom-1.8.1-cp39-cp39-win_amd64.whl", hash = "sha256:edbd1c333c36b019164b01e20fbee842e6795da5769db106afa53dfcd65e6be2", size = 68185, upload-time = "2025-04-02T02:51:48.739603Z" },
    { url = "https://files.pythonhosted.org/packages/6c/b7/7044859b4b6cce0c4d9c2731198ad3970425dda1824a0cc64db94b379054/lilcom-1.8.1-cp311-cp311-macosx_10_9_universal2.whl", hash = "sha256:13e7384675119f34504e44821d6baf8d9696dd2ed77ba54a392cd79d22c376f2", size = 125275, upload-time = "2025-04-02T02:51:01.293120Z" },
    { url = "https://files.pythonhosted.org/packages/76/15/78f1a44a2a98be5830e7d6a7f37e9b7b18475d3b65454adec13348bdf78b/lilcom-1.8.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:075b3155e37d2964ce47dc5d456c9afe3f5aace0f48e33236b0ca126e7f2d757", size = 88439, upload-time = "2025-04-02T02:52:05.228605Z" },
    { url = "https://files.pythonhosted.org/packages/78/1e/4bca706dc50230146b168d5c52403ec4e144650999fae2150a0e60ed7303/lilcom-1.8.1-cp312-cp312-macosx_10_13_universal2.whl", hash = "sha256:b0ace9d4f95199266a36d1144214ff2056679ddb44462f75326a0b9fbf296928", size = 124607, upload-time = "2025-04-02T02:49:22.243620Z" },
    { url = "https://files.pythonhosted.org/packages/7b/02/30e76ca2bfc3fe19adbcca254dde03ba48a6e623eb55df2752f4c06cfeb0/lilcom-1.8.1-cp310-cp310-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:7460e2dd481b38fc8fa1f0cc48c5aaa1b4206d0c27130c001bf23f1d4c99143b", size = 98968, upload-time = "2025-04-02T02:54:34.177254Z" },
    { url = "https://files.pythonhosted.org/packages/7c/0d/f8be338de1d45d6a6fc26a24d0ad9f6be0a94130b5b7687c2cc08a5be099/lilcom-1.8.1-cp312-cp312-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:23b45cb5b966999826eb1aa80154d392550902ef26374dc628a8c576d844d548", size = 98796, upload-time = "2025-04-02T02:54:47.920422Z" },
    { url = "https://files.pythonhosted.org/packages/82/1a/86e3f8a6fb5a1700a129da45490de1572c8606ad6471c849dbd9a6d452c0/lilcom-1.8.1-cp39-cp39-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:a4e2d9bc486ca422bd614ec386e83f36cbe1ad20d7d362044ef86f440aa66b9d", size = 99541, upload-time = "2025-04-02T02:53:30.103395Z" },
    { url = "https://files.pythonhosted.org/packages/84/da/3b8a45be54f4d12a2d118c84d9d2aab81e5b75ae4a7b8469213a28b121dd/lilcom-1.8.1-cp310-cp310-win_amd64.whl", hash = "sha256:c254a74156ff8da2e43c8b891ed47eefcf0c1fee82a0c5984388052d97573a1b", size = 68524, upload-time = "2025-04-02T02:49:48.076019Z" },
    { url = "https://files.pythonhosted.org/packages/a5/d7/ff0a2bd3370267eeb0d4593111ddd613827c8a09ab13997a69018e4e8942/lilcom-1.8.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:eaa4d3ccec192146b21bbb12c1b518df5efd2e6381a74c6c2af7878cdc51bf28", size = 94629, upload-time = "2025-04-02T02:49:53.328678Z" },
    { url = "https://files.pythonhosted.org/packages/bd/02/2c329139ef8615c689f4a402e46c7c9029110eab14ca4685aef7ecf0593f/lilcom-1.8.1-cp313-cp313-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:1267644b383a7b9f64ba5074b459e3f91635363fb36824c81205774f31b6e1c8", size = 98991, upload-time = "2025-04-02T02:53:54.959937Z" },
    { url = "https://files.pythonhosted.org/packages/be/e5/79e8ac007fea956eccfc5df73fc6212f1ec49848552b5c134f92f110fd7d/lilcom-1.8.1-cp38-cp38-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:486259b0bf1a3b84bf5e6055f14d5a3fa2dd7246a2f5d114186a58b25f011174", size = 99707, upload-time = "2025-04-02T02:53:59.556922Z" },
    { url = "https://files.pythonhosted.org/packages/c3/7f/bd4e63c9afea69f4130ef32d824530a62a628007012eb9cf9661509c60fe/lilcom-1.8.1-cp313-cp313-macosx_10_13_universal2.whl", hash = "sha256:a37956d17c9657177781391b5b4213f554737ae6bf8a5d37cd11465a221f1832", size = 124650, upload-time = "2025-04-02T02:51:00.711109Z" },
    { url = "https://files.pythonhosted.org/packages/c7/9a/16b944bf1d3c18637e759a059433537d5a54131decc2138a81d5834fc5a3/lilcom-1.8.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:bb8b1b76ab81b1c7953d25c80e7880d31c8fbc4b63da2c6375c6151332017da1", size = 93484, upload-time = "2025-04-02T02:53:56.329583Z" },
    { url = "https://files.pythonhosted.org/packages/d5/cc/46f2bcd812a4039bd55633b10d5146466b295dea378d6c84facc7a55c8db/lilcom-1.8.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:defce157d05bf8bdef9e0c5d2346a9088a3b939ef653475a11e627b90802e501", size = 94252, upload-time = "2025-04-02T02:53:33.410582Z" },
    { url = "https://files.pythonhosted.org/packages/d7/cd/e3e45ef07c2e19f5718d7c9d33b40438b83a3397bdd4c70bd3d1bbf059ad/lilcom-1.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:9bdeea4aa3d7cad9e38cac99ef012a61f843a87a661b9475f565787f73828ec5", size = 92337, upload-time = "2025-04-02T02:54:35.391098Z" },
    { url = "https://files.pythonhosted.org/packages/db/94/9553e967a067e0579dd9be9658a428ae78aebde19d7c56d7478bf68cf48b/lilcom-1.8.1-cp312-cp312-win_amd64.whl", hash = "sha256:1eefd5b4735fca240aa35000dbe8a71e843fb00d64ccdc468c61eab03f23cf86", size = 69719, upload-time = "2025-04-02T02:50:48.892713Z" },
    { url = "https://files.pythonhosted.org/packages/dc/f6/ef61aa6436e82b3bf25344b9483c9663aa019058ad7257bc1f8be4bf4cb8/lilcom-1.8.1-cp39-cp39-macosx_10_9_universal2.whl", hash = "sha256:396db5bf76eafdf150aead20722166f73499211a5dd1849a8348ba8cef22392b", size = 122585, upload-time = "2025-04-02T02:48:48.122232Z" },
    { url = "https://files.pythonhosted.org/packages/e1/5c/51ece6a8f6ed39c27eb18bb1c09fe6508613bc67bcc5872caa788cdc9eef/lilcom-1.8.1-cp310-cp310-macosx_10_9_universal2.whl", hash = "sha256:7e896dd6172011d320c26a4ca648edddf1e6b47bb1de749cf27ac096d73f63c9", size = 122436, upload-time = "2025-04-02T02:49:37.012651Z" },
    { url = "https://files.pythonhosted.org/packages/e3/6e/7868a5a90e66fefa60642682f5551cb75e489c603f155367003b88363af3/lilcom-1.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:08ba2cf1cd9a175ec3b791ea727e981a1cd25a03d39c32264d651bc52e7e5c33", size = 92958, upload-time = "2025-04-02T02:54:48.822896Z" },
    { url = "https://files.pythonhosted.org/packages/e3/b3/547df557392043fc71c0c070b1adcf6b3503950461db820ab9f253432abd/lilcom-1.8.1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:91cbc4495506f2e567f9b5d140c29dcd3cd1060264421943cad1ad16b996d7db", size = 89855, upload-time = "2025-04-02T02:51:44.303033Z" },
    { url = "https://files.pythonhosted.org/packages/e6/b2/e1bf427a50b5ad2b65482abad26b51e13f4dea74743e5f698e48e29be3fe/lilcom-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:cfd52b915cbbd923f063e71a40b7751bf659c6bda62bcab03b45dac48c1c8633", size = 92337, upload-time = "2025-04-02T02:54:00.534467Z" },
    { url = "https://files.pythonhosted.org/packages/f2/9b/d140ff7601968c85cae2b99ea4a5706eac7ffaa11eb152dcc42c124bbfb7/lilcom-1.8.1-cp37-cp37m-manylinux_2_17_i686.manylinux2014_i686.whl", hash = "sha256:7698045b3998715bd2522c88b4ec2296ffb6a7ce330a1602776d49f6dc80a56b", size = 102788, upload-time = "2025-04-02T02:49:52.379904Z" },
]

**Comment by jmbreuer** [comment]
How would I apply this workaround?

My setup so far is a `docker-compose.yml`:

``` docker-compose.yml
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:v1.2.0
    ports:
      - "8080:8080"
    volumes:
      - scriberr_data:/app/data # volume for data
      - env_data:/app/whisperx-env # volume for models and python envs
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - APP_ENV=production # DO NOT CHANGE THIS
      # CORS: comma-separated list of allowed origins for production
      # - ALLOWED_ORIGINS=https://your-domain.com
      # - SECURE_COOKIES=false # Uncomment this ONLY if you are not using SSL
    restart: unless-stopped

volumes:
  scriberr_data: {}
  env_data: {}
```

**Comment by rishikanthc** [comment]
Hi ! Apologies for this. I am seeing a lot of issues for the CUDA docker images. I do plan on fixing it but it's going to be a while. 

I just wanted to let you know that development is temporarily paused but not abandoned. See [README](https://github.com/rishikanthc/Scriberr#update-on-project-status) for details, and thanks for your patience! Things should resume soon once I get back up on my feet.

**Comment by rishikanthc** [comment]
Hi all ! I know it's been a while since this issue was opened and folks might be wondering why there hasn't been any updates.
I just wanted to let you know that development is temporarily paused but not abandoned. I recently got laid off and am urgently trying to find my next job. See [README](https://github.com/rishikanthc/Scriberr#update-on-project-status) for details, and thanks for your patience! Things should resume soon once I get back up on my feet.
